window.CUSDIS_LOCALE = {
  powered_by: 'Powered by Cusdis',
  post_comment: 'コメントする',
  loading: '読み込み中...',
  email: 'Eメール（任意）',
  nickname: 'お名前（任意）',
  reply_placeholder: '内容',
  reply_btn: 'コメントする',
  sending: '送信中...',
  mod_badge: '管理者',
  content_is_required: '内容は必須です',
  nickname_is_required: '',
  comment_has_been_sent: 'コメントが送信されました',
  comments: 'コメント',
  likes: 'いいね',
  reply: '返信',
  cancel_reply: '返信をキャンセル',
  collapse: '折りたたむ',
  expand: '展開',
  no_comments: 'まだコメントはありません',
  sort_by: '並び替え',
  oldest: '古い順',
  newest: '新しい順',
  best: '人気順',
  edit_nickname: 'お名前を編集',
  edit_nickname_btn: '保存',
  email_notice: 'メールアドレスは公開されません',
};
